package mapper

import (
	"reflect"

	"github.com/qjebbs/go-sqlb"
	"github.com/qjebbs/go-sqlb/dialect"
	"github.com/qjebbs/go-sqlb/tag"
	"github.com/qjebbs/go-sqlf/v4"
)

// selectableModel is the interface that a model struct should implement to be used in Select with struct mapping.
// It's unexported and not implemented by users directly, but generated by codegen tools.
type selectableModel[T any] interface {
	New() T
	Fields() []*Field
	Values() []any
}

// Field represents a struct field parsed and generated by codegen tools.
type Field struct {
	Tags   *tag.Info
	Diving bool
}

func _selectModel[T any](ctx sqlb.Context, db QueryAble, b SelectBuilder, model selectableModel[T], options ...Option) ([]T, error) {
	opt := mergeOptions(options...)
	var debugger *debugger
	if opt.debug {
		debugger = newDebugger("Select", model, opt)
		defer debugger.print(ctx.BaseDialect())
	}
	queryStr, args, indexes, err := buildSelectQueryForModel(ctx, ctx.Dialect(), b, model, opt)
	if err != nil {
		return nil, err
	}
	if debugger != nil {
		debugger.onBuilt(queryStr, args)
	}
	if db == nil {
		return nil, ErrNilDB
	}
	return scan(ctx, db, queryStr, args, debugger, func() (T, []any) {
		m := model.New()
		values := model.Values()
		var dests []any
		for i, value := range values {
			if len(indexes) < len(values) {
				if _, ok := indexes[i]; !ok {
					continue
				}
			}
			dests = append(dests, value)
		}
		return m, dests
	})
}

func buildSelectQueryForModel[T any](ctx sqlb.Context, d dialect.Dialect, b SelectBuilder, model selectableModel[T], opt *Options) (query string, args []any, dests map[int]struct{}, err error) {
	if opt == nil {
		opt = newDefaultOptions()
	}

	fields := model.Fields()
	values := model.Values()
	dests = make(map[int]struct{}, len(fields))
	var columns []sqlf.Builder
	for i, field := range fields {
		if field.Tags.Column == "" && field.Tags.Select == "" {
			continue
		}
		if !opt.selectTags.Match(field.Tags.SelectOn) {
			continue
		}
		dests[i] = struct{}{}
		column, err := buildSelectColumn(d, field.Tags, reflect.TypeOf(values[i]).Elem(), opt)
		if err != nil {
			return "", nil, nil, err
		}
		columns = append(columns, column)
	}
	b.SetSelect(columns...)
	query, args, err = sqlf.Build(ctx, b)
	if err != nil {
		return "", nil, nil, err
	}
	return query, args, dests, nil
}
