package mapper

import (
	"reflect"

	"github.com/qjebbs/go-sqlb"
	"github.com/qjebbs/go-sqlb/dialect"
	"github.com/qjebbs/go-sqlb/tag"
	"github.com/qjebbs/go-sqlf/v4"
)

// selectableModel is the interface that a model struct should implement to be used in Select with struct mapping.
// It's unexported and not implemented by users directly, but generated by codegen tools.
type selectableModel[T any] interface {
	New() T
	Tags() []*tag.Info
	Values() []any
	FillValues(dests []any, indexes []int)
}

func _selectModel[T any](ctx sqlb.Context, db QueryAble, b SelectBuilder, model selectableModel[T], options ...Option) ([]T, error) {
	opt := mergeOptions(options...)
	var debugger *debugger
	if opt.debug {
		debugger = newDebugger("Select", model, opt)
		defer debugger.print(ctx.BaseDialect())
	}
	queryStr, args, indexes, err := buildSelectQueryForModel(ctx, ctx.Dialect(), b, model, opt)
	if err != nil {
		return nil, err
	}
	if debugger != nil {
		debugger.onBuilt(queryStr, args)
	}
	if db == nil {
		return nil, ErrNilDB
	}
	return scan(ctx, db, queryStr, args, debugger, func() (T, []any) {
		m := model.New()
		values := make([]any, len(indexes))
		// Prepare the slice of destinations for sql.Rows.Scan().
		//
		// PERFORMANCE-CRITICAL:
		// The `FillValues` method is intentionally designed not to return a slice. Instead,
		// we pre-allocate the `values` slice here and pass it in to be filled.
		//
		// This design is crucial for escape analysis. When a function returns a slice (or any pointer type),
		// the compiler must assume it will be used beyond the function's scope and allocates it on the heap.
		// By creating the slice here and using it only within this factory function, we signal to the
		// compiler that the slice's lifetime is confined. This gives the compiler the opportunity
		// to perform an optimization and allocate the `values` slice on the stack instead of the heap,
		// effectively making this part of the scan preparation a zero-allocation operation.
		any(m).(selectableModel[T]).FillValues(values, indexes)
		return m, values
	})
}

func buildSelectQueryForModel[T any](ctx sqlb.Context, d dialect.Dialect, b SelectBuilder, model selectableModel[T], opt *Options) (query string, args []any, dests []int, err error) {
	if opt == nil {
		opt = newDefaultOptions()
	}

	tags := model.Tags()
	values := model.Values()
	dests = make([]int, 0, len(tags))
	var columns []sqlf.Builder
	for i, tag := range tags {
		if tag.Column == "" && tag.Select == "" {
			continue
		}
		if !opt.selectTags.Match(tag.SelectOn) {
			continue
		}
		dests = append(dests, i)
		column, err := buildSelectColumn(d, tag, reflect.TypeOf(values[i]).Elem(), opt)
		if err != nil {
			return "", nil, nil, err
		}
		columns = append(columns, column)
	}
	b.SetSelect(columns...)
	query, args, err = sqlf.Build(ctx, b)
	if err != nil {
		return "", nil, nil, err
	}
	return query, args, dests, nil
}
