package mapper

import (
	"fmt"
	"reflect"

	"github.com/qjebbs/go-sqlb"
	"github.com/qjebbs/go-sqlb/dialect"
	"github.com/qjebbs/go-sqlf/v4"
)

// selectableModel is the interface that a model struct should implement to be used in Select with struct mapping.
// It's unexported and not implemented by users directly, but generated by codegen tools.
type selectableModel[T any] interface {
	New() T
	Columns(tags SelectTags, alias ...string) []*sqlb.Column
	Values(tags SelectTags) []any
}

func _selectModel[T any](ctx sqlb.Context, db QueryAble, b SelectBuilder, model selectableModel[T], options ...Option) ([]T, error) {
	opt := mergeOptions(options...)
	var debugger *debugger
	if opt.debug {
		debugger = newDebugger("Select", model, opt)
		defer debugger.print(ctx.BaseDialect())
	}
	queryStr, args, err := buildSelectQueryForModel(ctx, ctx.Dialect(), b, model, opt)
	if err != nil {
		return nil, err
	}
	if debugger != nil {
		debugger.onBuilt(queryStr, args)
	}
	if db == nil {
		return nil, ErrNilDB
	}
	return scan(ctx, db, queryStr, args, debugger, func() (T, []any) {
		dest := model.New()
		fields := model.Values(opt.selectTags)
		return dest, fields
	})
}

func buildSelectQueryForModel[T any](ctx sqlb.Context, d dialect.Dialect, b SelectBuilder, model selectableModel[T], opt *Options) (query string, args []any, err error) {
	if opt == nil {
		opt = newDefaultOptions()
	}

	columns := model.Columns(opt.selectTags)
	dests := model.Values(opt.selectTags)
	builders := make([]sqlf.Builder, len(columns))
	for i, column := range columns {
		builders[i] = column
		if opt.enableNullZero(column.Table.Name) {
			colType := reflect.TypeOf(dests[i])
			if dialect.CheckNullCoalesceable(colType) {
				c, err := d.NullCoalesce(column, colType)
				if err != nil {
					return "", nil, fmt.Errorf("field %s: %w", column.Name, err)
				}
				if c != nil {
					builders[i] = c
				}
			}
		}
	}
	b.SetSelect(builders...)
	query, args, err = sqlf.Build(ctx, b)
	if err != nil {
		return "", nil, err
	}
	return query, args, nil
}
